### ISSUE TITLE
Support for Python 2.x

### ISSUE THREAD

**Issue by ankur-agrawal-elucidata** [koaning/kadro#9]
Hey, can we add support for python 2.x.

**Comment by koaning** [comment]
If you're willing to submit a pull request I would be willing to review it but I doubt it is worth the effort. 

1. Pandas is in a bit of flux. It seems like pandas is adding features that may make this library redundant. 
2. This is currently a bit of a hobby project so I wouldn't want to spend too much time on it.  
3. Python 3 is the way forward.
